//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sfa.Das.Sas.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EquivalenceLevels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EquivalenceLevels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sfa.Das.Sas.Resources.EquivalenceLevels", typeof(EquivalenceLevels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doctorate.
        /// </summary>
        public static string EighthLevel {
            get {
                return ResourceManager.GetString("EighthLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foundation degree.
        /// </summary>
        public static string FifthLevel {
            get {
                return ResourceManager.GetString("FifthLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCSEs at grades D to G.
        /// </summary>
        public static string FirstLevel {
            get {
                return ResourceManager.GetString("FirstLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to certificate of higher education.
        /// </summary>
        public static string FourthLevel {
            get {
                return ResourceManager.GetString("FourthLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCSEs at grades A* to C.
        /// </summary>
        public static string SecondLevel {
            get {
                return ResourceManager.GetString("SecondLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to master’s degree.
        /// </summary>
        public static string SeventhLevel {
            get {
                return ResourceManager.GetString("SeventhLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bachelor&apos;s degree.
        /// </summary>
        public static string SixthLevel {
            get {
                return ResourceManager.GetString("SixthLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A levels at grades A to E.
        /// </summary>
        public static string ThirdLevel {
            get {
                return ResourceManager.GetString("ThirdLevel", resourceCulture);
            }
        }
    }
}
