// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VacanciesApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BadRequestError
    {
        /// <summary>
        /// Initializes a new instance of the BadRequestError class.
        /// </summary>
        public BadRequestError()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BadRequestError class.
        /// </summary>
        public BadRequestError(string errorCode = default(string), string errorMessage = default(string))
        {
            ErrorCode = errorCode;
            ErrorMessage = errorMessage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorCode")]
        public string ErrorCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorMessage")]
        public string ErrorMessage { get; set; }

    }
}
