parameters:
  ServiceConnection:
  SolutionBaseName:
  Environment:
  OverrideBlockOnPossibleDataLoss:

jobs:
  - deployment: DeployWebApp
    pool:
      name: DAS - Continuous Deployment Agents
    environment: ${{ parameters.Environment }}
    variables:
      DigengResourceGroupName: "das-$(ResourceEnvironmentName)-digeng-rg"
      DigengStorageAccountName: "das$(ResourceEnvironmentName)digengstr"
    strategy:
      runOnce:
        deploy:
          steps:
            - template: azure-pipelines-templates/deploy/step/wait-azure-devops-deployment.yml@das-platform-building-blocks
              parameters:
                ServiceConnection: ${{ parameters.ServiceConnection }}
                EnvironmentId: $(Environment.Id)
                PipelineName: $(Build.DefinitionName)
                RunId: $(Build.BuildId)
            - template: azure-pipelines-templates/deploy/step/set-backendaccessrestrictions-variable.yml@das-platform-building-blocks
              parameters:
                ServiceConnection: ${{ parameters.ServiceConnection }}
                SharedEnvResourceGroup: $(SharedEnvResourceGroup)
                SharedEnvVirtualNetworkName: $(SharedEnvVirtualNetworkName)
                BackEndAccessRestrictionsExcludedSubnets: $(BackEndAccessRestrictionsExcludedSubnets)
                ResourceEnvironmentName: $(ResourceEnvironmentName)
                UnrestrictedEnvironments: $(UnrestrictedEnvironments)
                UptimeMonitoringAccessRestrictions: $(UptimeMonitoringAccessRestrictions)
            - template: azure-pipelines-templates/deploy/step/arm-deploy.yml@das-platform-building-blocks
              parameters:
                ServiceConnection: ${{ parameters.ServiceConnection }}
                SubscriptionId: $(SubscriptionId)
                Location: $(ResourceGroupLocation)
                Environment: ${{ parameters.Environment }}
                TemplatePath: $(Pipeline.Workspace)/${{ parameters.SolutionBaseName }}/azure/template.json
                ParametersPath: $(Pipeline.Workspace)/${{ parameters.SolutionBaseName }}/azure/template.parameters.json
                IsMultiRepoCheckout: true
                TemplateSecrets:
                  LoggingRedisConnectionString: $(LoggingRedisConnectionString)
                  ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)
            - template: azure-pipelines-templates/deploy/step/sql-dacpac-deploy.yml@das-platform-building-blocks
              parameters:
                AzureSubscription: ${{ parameters.ServiceConnection }}
                ServerName: $(SharedSQLServerFQDN)
                SqlUsername: $(SharedSQLServerUsername)
                DacpacFile: $(Pipeline.Workspace)/DacpacArtifact/src/SFA.DAS.Campaign.Database/bin/Output/SFA.DAS.Campaign.Database.dacpac
                DatabaseName: $(DatabaseName)
                OverrideBlockOnPossibleDataLoss: ${{ parameters.OverrideBlockOnPossibleDataLoss }}
                Environment: ${{ parameters.Environment }}
            - template: azure-pipelines-templates/deploy/step/get-apim-subscription-key.yml@das-platform-building-blocks
              parameters:
                ServiceConnection: ${{ parameters.ServiceConnection }}
                ApimResourceGroup: $(SharedApimResourceGroup)
                ApimName: $(SharedApimName)
                SubscriptionId: $(AppServiceName)
                PipelineVariableName: CampaignApimSubscriptionKey
                IsMultiRepoCheckout: true
            - task: AzurePowerShell@5
              displayName: "Get Digeng Storage Account Connection String"
              inputs:
                azureSubscription: ${{ parameters.ServiceConnection }}
                ScriptPath: "$(Pipeline.Workspace)/das-platform-automation/Infrastructure-Scripts/Get-StorageAccountConnectionString.ps1"
                ScriptArguments: '-ResourceGroup "$(DigengResourceGroupName)" -StorageAccount "$(DigengStorageAccountName)" -OutputVariable "DigEngQueuesStorageConnectionString"'
                FailOnStandardError: true
                azurePowerShellVersion: LatestVersion
                pwsh: true
            - template: azure-pipelines-templates/deploy/step/generate-config.yml@das-platform-building-blocks
              parameters:
                EnvironmentName: $(EnvironmentName)
                ServiceConnection: ${{ parameters.ServiceConnection }}
                SourcePath: $(Pipeline.Workspace)/das-employer-config/Configuration/das-csjproxy-api
                StorageAccountName: $(ConfigurationStorageAccountName)
                StorageAccountResourceGroup: $(SharedEnvResourceGroup)
                TargetFileName: "*.schema.json"
                TableName: Configuration
                ConfigurationSecrets: {} # remove this if there are no secrets that need to be mapped for config
            - template: azure-pipelines-templates/deploy/step/app-deploy.yml@das-platform-building-blocks
              parameters:
                ServiceConnection: ${{ parameters.ServiceConnection }}
                AppServiceName: $(AppServiceName)
                DeploymentPackagePath: $(Pipeline.Workspace)/${{ parameters.SolutionBaseName }}/${{ parameters.SolutionBaseName }}.Web.zip
