CREATE TABLE dbo.UserData
(
	Id					INT NOT NULL PRIMARY KEY,
	FirstName			VARCHAR(250) NOT NULL,
	LastName			VARCHAR(250) NOT NULL,
	Email				VARCHAR(250) NOT NULL,
	UkEmployerSize		VARCHAR(50) NOT NULL,
	PrimaryIndustry		VARCHAR(50) NOT NULL,
	PrimaryLocation		VARCHAR(50) NOT NULL,
	AppsgovSignUpDate	DATETIME NOT NULL,
	PersonOrigin		VARCHAR(50) NULL,
	IncludeInUR			BIT NULL
) ON [PRIMARY]
GO