/* 
 * IfA Standards API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Ifa.Api.Model
{
    /// <summary>
    /// ApiDutyDataModel
    /// </summary>
    [DataContract]
    public partial class ApiDutyDataModel :  IEquatable<ApiDutyDataModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiDutyDataModel" /> class.
        /// </summary>
        /// <param name="dutyDetail">dutyDetail.</param>
        /// <param name="isThisACoreDuty">isThisACoreDuty.</param>
        /// <param name="mappedBehaviour">mappedBehaviour.</param>
        /// <param name="mappedKnowledge">mappedKnowledge.</param>
        /// <param name="mappedOptions">mappedOptions.</param>
        /// <param name="mappedSkills">mappedSkills.</param>
        /// <param name="dutyID">dutyID.</param>
        /// <param name="criteriaForMeasuringPerformance">criteriaForMeasuringPerformance.</param>
        public ApiDutyDataModel(string dutyDetail = default(string), bool isThisACoreDuty = default(bool), List<ApiBehaviourDataModel> mappedBehaviour = default(List<ApiBehaviourDataModel>), List<ApiKnowledgeDataModel> mappedKnowledge = default(List<ApiKnowledgeDataModel>), List<ApiOptionDataModel> mappedOptions = default(List<ApiOptionDataModel>), List<ApiSkillDataModel> mappedSkills = default(List<ApiSkillDataModel>), string dutyID = default(string), string criteriaForMeasuringPerformance = default(string))
        {
            this.DutyDetail = dutyDetail;
            this.IsThisACoreDuty = isThisACoreDuty;
            this.MappedBehaviour = mappedBehaviour;
            this.MappedKnowledge = mappedKnowledge;
            this.MappedOptions = mappedOptions;
            this.MappedSkills = mappedSkills;
            this.DutyID = dutyID;
            this.CriteriaForMeasuringPerformance = criteriaForMeasuringPerformance;
        }
        
        /// <summary>
        /// Gets or Sets DutyDetail
        /// </summary>
        [DataMember(Name="dutyDetail", EmitDefaultValue=false)]
        public string DutyDetail { get; set; }

        /// <summary>
        /// Gets or Sets IsThisACoreDuty
        /// </summary>
        [DataMember(Name="isThisACoreDuty", EmitDefaultValue=false)]
        public bool IsThisACoreDuty { get; set; }

        /// <summary>
        /// Gets or Sets MappedBehaviour
        /// </summary>
        [DataMember(Name="mappedBehaviour", EmitDefaultValue=false)]
        public List<ApiBehaviourDataModel> MappedBehaviour { get; set; }

        /// <summary>
        /// Gets or Sets MappedKnowledge
        /// </summary>
        [DataMember(Name="mappedKnowledge", EmitDefaultValue=false)]
        public List<ApiKnowledgeDataModel> MappedKnowledge { get; set; }

        /// <summary>
        /// Gets or Sets MappedOptions
        /// </summary>
        [DataMember(Name="mappedOptions", EmitDefaultValue=false)]
        public List<ApiOptionDataModel> MappedOptions { get; set; }

        /// <summary>
        /// Gets or Sets MappedSkills
        /// </summary>
        [DataMember(Name="mappedSkills", EmitDefaultValue=false)]
        public List<ApiSkillDataModel> MappedSkills { get; set; }

        /// <summary>
        /// Gets or Sets DutyID
        /// </summary>
        [DataMember(Name="dutyID", EmitDefaultValue=false)]
        public string DutyID { get; set; }

        /// <summary>
        /// Gets or Sets CriteriaForMeasuringPerformance
        /// </summary>
        [DataMember(Name="criteriaForMeasuringPerformance", EmitDefaultValue=false)]
        public string CriteriaForMeasuringPerformance { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApiDutyDataModel {\n");
            sb.Append("  DutyDetail: ").Append(DutyDetail).Append("\n");
            sb.Append("  IsThisACoreDuty: ").Append(IsThisACoreDuty).Append("\n");
            sb.Append("  MappedBehaviour: ").Append(MappedBehaviour).Append("\n");
            sb.Append("  MappedKnowledge: ").Append(MappedKnowledge).Append("\n");
            sb.Append("  MappedOptions: ").Append(MappedOptions).Append("\n");
            sb.Append("  MappedSkills: ").Append(MappedSkills).Append("\n");
            sb.Append("  DutyID: ").Append(DutyID).Append("\n");
            sb.Append("  CriteriaForMeasuringPerformance: ").Append(CriteriaForMeasuringPerformance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApiDutyDataModel);
        }

        /// <summary>
        /// Returns true if ApiDutyDataModel instances are equal
        /// </summary>
        /// <param name="input">Instance of ApiDutyDataModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiDutyDataModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DutyDetail == input.DutyDetail ||
                    (this.DutyDetail != null &&
                    this.DutyDetail.Equals(input.DutyDetail))
                ) && 
                (
                    this.IsThisACoreDuty == input.IsThisACoreDuty ||
                    this.IsThisACoreDuty.Equals(input.IsThisACoreDuty)
                ) && 
                (
                    this.MappedBehaviour == input.MappedBehaviour ||
                    this.MappedBehaviour != null &&
                    input.MappedBehaviour != null &&
                    this.MappedBehaviour.SequenceEqual(input.MappedBehaviour)
                ) && 
                (
                    this.MappedKnowledge == input.MappedKnowledge ||
                    this.MappedKnowledge != null &&
                    input.MappedKnowledge != null &&
                    this.MappedKnowledge.SequenceEqual(input.MappedKnowledge)
                ) && 
                (
                    this.MappedOptions == input.MappedOptions ||
                    this.MappedOptions != null &&
                    input.MappedOptions != null &&
                    this.MappedOptions.SequenceEqual(input.MappedOptions)
                ) && 
                (
                    this.MappedSkills == input.MappedSkills ||
                    this.MappedSkills != null &&
                    input.MappedSkills != null &&
                    this.MappedSkills.SequenceEqual(input.MappedSkills)
                ) && 
                (
                    this.DutyID == input.DutyID ||
                    (this.DutyID != null &&
                    this.DutyID.Equals(input.DutyID))
                ) && 
                (
                    this.CriteriaForMeasuringPerformance == input.CriteriaForMeasuringPerformance ||
                    (this.CriteriaForMeasuringPerformance != null &&
                    this.CriteriaForMeasuringPerformance.Equals(input.CriteriaForMeasuringPerformance))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DutyDetail != null)
                    hashCode = hashCode * 59 + this.DutyDetail.GetHashCode();
                hashCode = hashCode * 59 + this.IsThisACoreDuty.GetHashCode();
                if (this.MappedBehaviour != null)
                    hashCode = hashCode * 59 + this.MappedBehaviour.GetHashCode();
                if (this.MappedKnowledge != null)
                    hashCode = hashCode * 59 + this.MappedKnowledge.GetHashCode();
                if (this.MappedOptions != null)
                    hashCode = hashCode * 59 + this.MappedOptions.GetHashCode();
                if (this.MappedSkills != null)
                    hashCode = hashCode * 59 + this.MappedSkills.GetHashCode();
                if (this.DutyID != null)
                    hashCode = hashCode * 59 + this.DutyID.GetHashCode();
                if (this.CriteriaForMeasuringPerformance != null)
                    hashCode = hashCode * 59 + this.CriteriaForMeasuringPerformance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
