/* 
 * IfA Standards API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Ifa.Api.Client.OpenAPIDateConverter;

namespace Ifa.Api.Model
{
    /// <summary>
    /// ApiRegulatedStandardData
    /// </summary>
    [DataContract]
    public partial class ApiRegulatedStandardData :  IEquatable<ApiRegulatedStandardData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiRegulatedStandardData" /> class.
        /// </summary>
        /// <param name="approved">approved.</param>
        /// <param name="name">name.</param>
        /// <param name="webLink">webLink.</param>
        public ApiRegulatedStandardData(bool approved = default(bool), string name = default(string), string webLink = default(string))
        {
            this.Approved = approved;
            this.Name = name;
            this.WebLink = webLink;
        }
        
        /// <summary>
        /// Gets or Sets Approved
        /// </summary>
        [DataMember(Name="approved", EmitDefaultValue=false)]
        public bool Approved { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets WebLink
        /// </summary>
        [DataMember(Name="webLink", EmitDefaultValue=false)]
        public string WebLink { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApiRegulatedStandardData {\n");
            sb.Append("  Approved: ").Append(Approved).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  WebLink: ").Append(WebLink).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApiRegulatedStandardData);
        }

        /// <summary>
        /// Returns true if ApiRegulatedStandardData instances are equal
        /// </summary>
        /// <param name="input">Instance of ApiRegulatedStandardData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiRegulatedStandardData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Approved == input.Approved ||
                    this.Approved.Equals(input.Approved)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.WebLink == input.WebLink ||
                    (this.WebLink != null &&
                    this.WebLink.Equals(input.WebLink))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Approved.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.WebLink != null)
                    hashCode = hashCode * 59 + this.WebLink.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
