/* 
 * IfA Standards API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Ifa.Api.Client;
using Ifa.Api.Model;

namespace Ifa.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFullStandardsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>TempApprenticeshipStandard</returns>
        TempApprenticeshipStandard FullStandardsGet (int? id);

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>ApiResponse of TempApprenticeshipStandard</returns>
        ApiResponse<TempApprenticeshipStandard> FullStandardsGetWithHttpInfo (int? id);
        /// <summary>
        /// Get a summarised list of Apprenticeship Standards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;TempApprenticeshipStandard&gt;</returns>
        List<TempApprenticeshipStandard> FullStandardsGetAll ();

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;TempApprenticeshipStandard&gt;</returns>
        ApiResponse<List<TempApprenticeshipStandard>> FullStandardsGetAllWithHttpInfo ();
        /// <summary>
        /// Get a summarised list of Apprenticeship Standards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;TempApprenticeshipStandard&gt;</returns>
        List<TempApprenticeshipStandard> FullStandardsGetAllHead ();

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;TempApprenticeshipStandard&gt;</returns>
        ApiResponse<List<TempApprenticeshipStandard>> FullStandardsGetAllHeadWithHttpInfo ();
        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>TempApprenticeshipStandard</returns>
        TempApprenticeshipStandard FullStandardsGetHead (int? id);

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>ApiResponse of TempApprenticeshipStandard</returns>
        ApiResponse<TempApprenticeshipStandard> FullStandardsGetHeadWithHttpInfo (int? id);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>Task of TempApprenticeshipStandard</returns>
        System.Threading.Tasks.Task<TempApprenticeshipStandard> FullStandardsGetAsync (int? id);

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>Task of ApiResponse (TempApprenticeshipStandard)</returns>
        System.Threading.Tasks.Task<ApiResponse<TempApprenticeshipStandard>> FullStandardsGetAsyncWithHttpInfo (int? id);
        /// <summary>
        /// Get a summarised list of Apprenticeship Standards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;TempApprenticeshipStandard&gt;</returns>
        System.Threading.Tasks.Task<List<TempApprenticeshipStandard>> FullStandardsGetAllAsync ();

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;TempApprenticeshipStandard&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<TempApprenticeshipStandard>>> FullStandardsGetAllAsyncWithHttpInfo ();
        /// <summary>
        /// Get a summarised list of Apprenticeship Standards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;TempApprenticeshipStandard&gt;</returns>
        System.Threading.Tasks.Task<List<TempApprenticeshipStandard>> FullStandardsGetAllHeadAsync ();

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;TempApprenticeshipStandard&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<TempApprenticeshipStandard>>> FullStandardsGetAllHeadAsyncWithHttpInfo ();
        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>Task of TempApprenticeshipStandard</returns>
        System.Threading.Tasks.Task<TempApprenticeshipStandard> FullStandardsGetHeadAsync (int? id);

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>Task of ApiResponse (TempApprenticeshipStandard)</returns>
        System.Threading.Tasks.Task<ApiResponse<TempApprenticeshipStandard>> FullStandardsGetHeadAsyncWithHttpInfo (int? id);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class FullStandardsApi : IFullStandardsApi
    {
        private Ifa.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="FullStandardsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FullStandardsApi(String basePath)
        {
            this.Configuration = new Ifa.Api.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Ifa.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FullStandardsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public FullStandardsApi(Ifa.Api.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Ifa.Api.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Ifa.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Ifa.Api.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Ifa.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>TempApprenticeshipStandard</returns>
        public TempApprenticeshipStandard FullStandardsGet (int? id)
        {
             ApiResponse<TempApprenticeshipStandard> localVarResponse = FullStandardsGetWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>ApiResponse of TempApprenticeshipStandard</returns>
        public ApiResponse< TempApprenticeshipStandard > FullStandardsGetWithHttpInfo (int? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling FullStandardsApi->FullStandardsGet");

            var localVarPath = "/api/FullStandards/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FullStandardsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TempApprenticeshipStandard>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (TempApprenticeshipStandard) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TempApprenticeshipStandard)));
        }

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>Task of TempApprenticeshipStandard</returns>
        public async System.Threading.Tasks.Task<TempApprenticeshipStandard> FullStandardsGetAsync (int? id)
        {
             ApiResponse<TempApprenticeshipStandard> localVarResponse = await FullStandardsGetAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>Task of ApiResponse (TempApprenticeshipStandard)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TempApprenticeshipStandard>> FullStandardsGetAsyncWithHttpInfo (int? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling FullStandardsApi->FullStandardsGet");

            var localVarPath = "/api/FullStandards/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FullStandardsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TempApprenticeshipStandard>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (TempApprenticeshipStandard) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TempApprenticeshipStandard)));
        }

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;TempApprenticeshipStandard&gt;</returns>
        public List<TempApprenticeshipStandard> FullStandardsGetAll ()
        {
             ApiResponse<List<TempApprenticeshipStandard>> localVarResponse = FullStandardsGetAllWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;TempApprenticeshipStandard&gt;</returns>
        public ApiResponse< List<TempApprenticeshipStandard> > FullStandardsGetAllWithHttpInfo ()
        {

            var localVarPath = "/api/FullStandards";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FullStandardsGetAll", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<TempApprenticeshipStandard>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<TempApprenticeshipStandard>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<TempApprenticeshipStandard>)));
        }

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;TempApprenticeshipStandard&gt;</returns>
        public async System.Threading.Tasks.Task<List<TempApprenticeshipStandard>> FullStandardsGetAllAsync ()
        {
             ApiResponse<List<TempApprenticeshipStandard>> localVarResponse = await FullStandardsGetAllAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;TempApprenticeshipStandard&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<TempApprenticeshipStandard>>> FullStandardsGetAllAsyncWithHttpInfo ()
        {

            var localVarPath = "/api/FullStandards";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FullStandardsGetAll", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<TempApprenticeshipStandard>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<TempApprenticeshipStandard>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<TempApprenticeshipStandard>)));
        }

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;TempApprenticeshipStandard&gt;</returns>
        public List<TempApprenticeshipStandard> FullStandardsGetAllHead ()
        {
             ApiResponse<List<TempApprenticeshipStandard>> localVarResponse = FullStandardsGetAllHeadWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;TempApprenticeshipStandard&gt;</returns>
        public ApiResponse< List<TempApprenticeshipStandard> > FullStandardsGetAllHeadWithHttpInfo ()
        {

            var localVarPath = "/api/FullStandards";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.HEAD, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FullStandardsGetAllHead", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<TempApprenticeshipStandard>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<TempApprenticeshipStandard>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<TempApprenticeshipStandard>)));
        }

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;TempApprenticeshipStandard&gt;</returns>
        public async System.Threading.Tasks.Task<List<TempApprenticeshipStandard>> FullStandardsGetAllHeadAsync ()
        {
             ApiResponse<List<TempApprenticeshipStandard>> localVarResponse = await FullStandardsGetAllHeadAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;TempApprenticeshipStandard&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<TempApprenticeshipStandard>>> FullStandardsGetAllHeadAsyncWithHttpInfo ()
        {

            var localVarPath = "/api/FullStandards";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.HEAD, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FullStandardsGetAllHead", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<TempApprenticeshipStandard>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<TempApprenticeshipStandard>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<TempApprenticeshipStandard>)));
        }

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>TempApprenticeshipStandard</returns>
        public TempApprenticeshipStandard FullStandardsGetHead (int? id)
        {
             ApiResponse<TempApprenticeshipStandard> localVarResponse = FullStandardsGetHeadWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>ApiResponse of TempApprenticeshipStandard</returns>
        public ApiResponse< TempApprenticeshipStandard > FullStandardsGetHeadWithHttpInfo (int? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling FullStandardsApi->FullStandardsGetHead");

            var localVarPath = "/api/FullStandards/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.HEAD, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FullStandardsGetHead", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TempApprenticeshipStandard>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (TempApprenticeshipStandard) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TempApprenticeshipStandard)));
        }

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>Task of TempApprenticeshipStandard</returns>
        public async System.Threading.Tasks.Task<TempApprenticeshipStandard> FullStandardsGetHeadAsync (int? id)
        {
             ApiResponse<TempApprenticeshipStandard> localVarResponse = await FullStandardsGetHeadAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>Task of ApiResponse (TempApprenticeshipStandard)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<TempApprenticeshipStandard>> FullStandardsGetHeadAsyncWithHttpInfo (int? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling FullStandardsApi->FullStandardsGetHead");

            var localVarPath = "/api/FullStandards/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.HEAD, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("FullStandardsGetHead", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<TempApprenticeshipStandard>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (TempApprenticeshipStandard) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(TempApprenticeshipStandard)));
        }

    }
}
