/* 
 * IfA Standards API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Ifa.Api.Client;
using Ifa.Api.Model;

namespace Ifa.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStandardsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>ApprenticeshipStandard</returns>
        ApprenticeshipStandard StandardsGet (int? id);

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>ApiResponse of ApprenticeshipStandard</returns>
        ApiResponse<ApprenticeshipStandard> StandardsGetWithHttpInfo (int? id);
        /// <summary>
        /// Get a summarised list of Apprenticeship Standards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;ApprenticeshipStandardSummary&gt;</returns>
        List<ApprenticeshipStandardSummary> StandardsGetAll ();

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;ApprenticeshipStandardSummary&gt;</returns>
        ApiResponse<List<ApprenticeshipStandardSummary>> StandardsGetAllWithHttpInfo ();
        /// <summary>
        /// Get a summarised list of Apprenticeship Standards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;ApprenticeshipStandardSummary&gt;</returns>
        List<ApprenticeshipStandardSummary> StandardsGetAllHead ();

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;ApprenticeshipStandardSummary&gt;</returns>
        ApiResponse<List<ApprenticeshipStandardSummary>> StandardsGetAllHeadWithHttpInfo ();
        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>ApprenticeshipStandard</returns>
        ApprenticeshipStandard StandardsGetHead (int? id);

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>ApiResponse of ApprenticeshipStandard</returns>
        ApiResponse<ApprenticeshipStandard> StandardsGetHeadWithHttpInfo (int? id);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>Task of ApprenticeshipStandard</returns>
        System.Threading.Tasks.Task<ApprenticeshipStandard> StandardsGetAsync (int? id);

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>Task of ApiResponse (ApprenticeshipStandard)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApprenticeshipStandard>> StandardsGetAsyncWithHttpInfo (int? id);
        /// <summary>
        /// Get a summarised list of Apprenticeship Standards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;ApprenticeshipStandardSummary&gt;</returns>
        System.Threading.Tasks.Task<List<ApprenticeshipStandardSummary>> StandardsGetAllAsync ();

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;ApprenticeshipStandardSummary&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ApprenticeshipStandardSummary>>> StandardsGetAllAsyncWithHttpInfo ();
        /// <summary>
        /// Get a summarised list of Apprenticeship Standards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;ApprenticeshipStandardSummary&gt;</returns>
        System.Threading.Tasks.Task<List<ApprenticeshipStandardSummary>> StandardsGetAllHeadAsync ();

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;ApprenticeshipStandardSummary&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ApprenticeshipStandardSummary>>> StandardsGetAllHeadAsyncWithHttpInfo ();
        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>Task of ApprenticeshipStandard</returns>
        System.Threading.Tasks.Task<ApprenticeshipStandard> StandardsGetHeadAsync (int? id);

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>Task of ApiResponse (ApprenticeshipStandard)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApprenticeshipStandard>> StandardsGetHeadAsyncWithHttpInfo (int? id);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class StandardsApi : IStandardsApi
    {
        private Ifa.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StandardsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StandardsApi(String basePath)
        {
            this.Configuration = new Ifa.Api.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Ifa.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StandardsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public StandardsApi(Ifa.Api.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Ifa.Api.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Ifa.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Ifa.Api.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Ifa.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>ApprenticeshipStandard</returns>
        public ApprenticeshipStandard StandardsGet (int? id)
        {
             ApiResponse<ApprenticeshipStandard> localVarResponse = StandardsGetWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>ApiResponse of ApprenticeshipStandard</returns>
        public ApiResponse< ApprenticeshipStandard > StandardsGetWithHttpInfo (int? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling StandardsApi->StandardsGet");

            var localVarPath = "/api/Standards/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StandardsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApprenticeshipStandard>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApprenticeshipStandard) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApprenticeshipStandard)));
        }

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>Task of ApprenticeshipStandard</returns>
        public async System.Threading.Tasks.Task<ApprenticeshipStandard> StandardsGetAsync (int? id)
        {
             ApiResponse<ApprenticeshipStandard> localVarResponse = await StandardsGetAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>Task of ApiResponse (ApprenticeshipStandard)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ApprenticeshipStandard>> StandardsGetAsyncWithHttpInfo (int? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling StandardsApi->StandardsGet");

            var localVarPath = "/api/Standards/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StandardsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApprenticeshipStandard>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApprenticeshipStandard) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApprenticeshipStandard)));
        }

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;ApprenticeshipStandardSummary&gt;</returns>
        public List<ApprenticeshipStandardSummary> StandardsGetAll ()
        {
             ApiResponse<List<ApprenticeshipStandardSummary>> localVarResponse = StandardsGetAllWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;ApprenticeshipStandardSummary&gt;</returns>
        public ApiResponse< List<ApprenticeshipStandardSummary> > StandardsGetAllWithHttpInfo ()
        {

            var localVarPath = "/api/Standards";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StandardsGetAll", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ApprenticeshipStandardSummary>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ApprenticeshipStandardSummary>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ApprenticeshipStandardSummary>)));
        }

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;ApprenticeshipStandardSummary&gt;</returns>
        public async System.Threading.Tasks.Task<List<ApprenticeshipStandardSummary>> StandardsGetAllAsync ()
        {
             ApiResponse<List<ApprenticeshipStandardSummary>> localVarResponse = await StandardsGetAllAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;ApprenticeshipStandardSummary&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<ApprenticeshipStandardSummary>>> StandardsGetAllAsyncWithHttpInfo ()
        {

            var localVarPath = "/api/Standards";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StandardsGetAll", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ApprenticeshipStandardSummary>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ApprenticeshipStandardSummary>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ApprenticeshipStandardSummary>)));
        }

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;ApprenticeshipStandardSummary&gt;</returns>
        public List<ApprenticeshipStandardSummary> StandardsGetAllHead ()
        {
             ApiResponse<List<ApprenticeshipStandardSummary>> localVarResponse = StandardsGetAllHeadWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;ApprenticeshipStandardSummary&gt;</returns>
        public ApiResponse< List<ApprenticeshipStandardSummary> > StandardsGetAllHeadWithHttpInfo ()
        {

            var localVarPath = "/api/Standards";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.HEAD, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StandardsGetAllHead", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ApprenticeshipStandardSummary>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ApprenticeshipStandardSummary>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ApprenticeshipStandardSummary>)));
        }

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;ApprenticeshipStandardSummary&gt;</returns>
        public async System.Threading.Tasks.Task<List<ApprenticeshipStandardSummary>> StandardsGetAllHeadAsync ()
        {
             ApiResponse<List<ApprenticeshipStandardSummary>> localVarResponse = await StandardsGetAllHeadAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a summarised list of Apprenticeship Standards 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;ApprenticeshipStandardSummary&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<ApprenticeshipStandardSummary>>> StandardsGetAllHeadAsyncWithHttpInfo ()
        {

            var localVarPath = "/api/Standards";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.HEAD, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StandardsGetAllHead", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ApprenticeshipStandardSummary>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ApprenticeshipStandardSummary>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ApprenticeshipStandardSummary>)));
        }

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>ApprenticeshipStandard</returns>
        public ApprenticeshipStandard StandardsGetHead (int? id)
        {
             ApiResponse<ApprenticeshipStandard> localVarResponse = StandardsGetHeadWithHttpInfo(id);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>ApiResponse of ApprenticeshipStandard</returns>
        public ApiResponse< ApprenticeshipStandard > StandardsGetHeadWithHttpInfo (int? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling StandardsApi->StandardsGetHead");

            var localVarPath = "/api/Standards/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.HEAD, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StandardsGetHead", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApprenticeshipStandard>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApprenticeshipStandard) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApprenticeshipStandard)));
        }

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>Task of ApprenticeshipStandard</returns>
        public async System.Threading.Tasks.Task<ApprenticeshipStandard> StandardsGetHeadAsync (int? id)
        {
             ApiResponse<ApprenticeshipStandard> localVarResponse = await StandardsGetHeadAsyncWithHttpInfo(id);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get an Apprenticeship Standard by the given ID,  if it exists 
        /// </summary>
        /// <exception cref="Ifa.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Standard ID</param>
        /// <returns>Task of ApiResponse (ApprenticeshipStandard)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ApprenticeshipStandard>> StandardsGetHeadAsyncWithHttpInfo (int? id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling StandardsApi->StandardsGetHead");

            var localVarPath = "/api/Standards/{id}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "text/html"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", this.Configuration.ApiClient.ParameterToString(id)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.HEAD, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("StandardsGetHead", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApprenticeshipStandard>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ApprenticeshipStandard) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApprenticeshipStandard)));
        }

    }
}
